/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";

export class ERC20Detailed extends Contract {
  functions: {
    balanceOf(who: string): Promise<BigNumber>;

    allowance(owner: string, spender: string): Promise<BigNumber>;

    approve(
      spender: string,
      value: number | string
    ): Promise<ContractTransaction>;

    transferFrom(
      from: string,
      to: string,
      value: number | string
    ): Promise<ContractTransaction>;

    transfer(to: string, value: number | string): Promise<ContractTransaction>;

    initialize(
      name: string,
      symbol: string,
      decimals: number | string
    ): Promise<ContractTransaction>;

    totalSupply(): Promise<BigNumber>;
    name(): Promise<string>;
    symbol(): Promise<string>;
    decimals(): Promise<BigNumber>;
  };
  filters: {
    Transfer(from: string | null, to: string | null, value: null): EventFilter;

    Approval(
      owner: string | null,
      spender: string | null,
      value: null
    ): EventFilter;
  };
}
