/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";

export class MinterRole extends Contract {
  functions: {
    isMinter(account: string): Promise<boolean>;

    initialize(sender: string): Promise<ContractTransaction>;

    addMinter(account: string): Promise<ContractTransaction>;

    renounceMinter(): Promise<ContractTransaction>;
  };
  filters: {
    MinterAdded(account: string | null): EventFilter;

    MinterRemoved(account: string | null): EventFilter;
  };
}
