/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";
import { TransactionOverrides } from ".";

export class SimpleStore extends Contract {
  functions: {
    setValue(
      value: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getValue(): Promise<string>;
  };
  filters: {
    ValueChanged(oldValue: null, newValue: null): EventFilter;
  };
}
